### ISSUE TITLE
[Bug] => Install broken

### ISSUE THREAD

**Issue by Rzqu** [theInfectedDrake/TIDoS-Framework#17]
Ive cloned the git to /opt directory, did the chmod as advised on the kitploit article and then run the ./install

Thing is, this then removes all the files from the directory and then the install bombs out leaving me an empty folder?

Running this on Kali Linux, ive attached the script output.

Not sure if anybody else is having this problem?

[tidos output.txt](https://github.com/theInfectedDrake/TIDoS-Framework/files/2277931/tidos.output.txt)

**Comment by theInfectedDrake** [comment]
Well, I have to say the instructions were not clear enough. Clone this tool in a different directory other than `/opt/`. What this install file does is install this project into the `/opt/` directory, and I purposefully did make arrangements for deleting files after every fresh setup since, after an update or a fresh clone, you wouldn't want the new version files to be messed with an older one. I will implement a further fix to this, but for now try cloning in a different directory and run the install. 🙂

**Comment by Rzqu** [comment]
That seems to have done the trick!

Thank you!

**Comment by s0md3v** [comment]
@theInfectedDrake You may want to do [this](https://github.com/s0md3v/Photon/blob/c3f5a3188732b4a8c7899a2730a79fe5852a2344/photon.py#L101-L102)
