### ISSUE TITLE
[Possible Bug] => Site seems to be down

### ISSUE THREAD

**Issue by Black-Lotus3301** [theInfectedDrake/TIDoS-Framework#21]
the first time using TIDoS it worked flawlessly and i had no issues whatsoever. then the second time i tried to use it, i put the web address in and it said that the "Site seems to be down". Again and again i tried to see if it would work but to no avail. i cant seem to figure this issue out.

**Comment by theInfectedDrake** [comment]
As far as I see here, this isn't a fault of TIDoS. 
So let me explain you the workflow what happens...
- You open the framework, and enter the url.
- TIDoS tries to do a reverse DNS lookup to find the IP address via socket.gethostbyname().
- If the IP is found, the site is declared as up, otherwise down.

So I guess it is your network connectivity that is causing this issue. If you still want me to take a look, I will need :
1. Your System Platform.
2. Your Python Version.
I will take a look definitely.

**Comment by theInfectedDrake** [comment]
I just told out a possible fix, can you confirm its working from your side?
