### ISSUE TITLE
[Possible Bug] => Unhandled runtime exception while execution

### ISSUE THREAD

**Issue by hinokop** [theInfectedDrake/TIDoS-Framework#26]
Hello,
I am getting this error nearly at every module I try to use. any ideas?

**Comment by theInfectedDrake** [comment]
I will need your system info and your Python version. 

I will presently refer this to #22, which had been resolved already, however there may be more unfixed bugs out there. Get me a list of some modules which are throwing out this error.

The error is possibly due to your 
- Bad internet connection.
- The host often going down.
- Firewall issues.

**Comment by hinokop** [comment]
OS: Parrot Security OS
Python Version 2.7.15rc1

**Comment by theInfectedDrake** [comment]
I guess I asked for a list if modules throwing out this error (only if there are any). I am closing this for now, but I will happy to reopen it if you hand me out a list of modules with their debug outputs.
