### ISSUE TITLE
pyexiv2 module not getiing installing in redhat 7

### ISSUE THREAD

**Issue by lnaphade** [theInfectedDrake/TIDoS-Framework#33]
[lalit@security TIDoS-Framework]$ sudo tidos
[sudo] password for lalit: 
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 31, in <module>
    from core.Auxillaries.auxil import *
  File "/opt/tidos/core/Auxillaries/auxil.py", line 23, in <module>
    from imgext import *
  File "modules/0x05-Auxillaries+PF6/imgext.py", line 16, in <module>
    from pyexiv2 import ImageMetadata, ExifTag
ImportError: No module named pyexiv2

I have tried with yum install pyexiv2.x86-x64
& pip install pyexiv2 & py3exiv2.

I have python3.6, python3 & python2.7 installed.

**Comment by theInfectedDrake** [comment]
Meh, is that a problem with TIDoS? Nope. Hence invalid issue.

Still since you have raised this issue, I would suggest you to install from [source](https://centos.pkgs.org/7/epel-x86_64/pyexiv2-0.3.2-22.el7.x86_64.rpm.html) if the install via `yum` in RHEL is getting broken by some means.

Also you might find [this thread](https://bugzilla.redhat.com/show_bug.cgi?id=1578525) useful in troubleshooting.

**Comment by 0xInfection** [comment]
This is to let you know, that the dependency `pyexiv2` has been removed from TIDoS's dependencies fire to its erring nature and incompatibility in various operating systems.
