### ISSUE TITLE
[Invalid] => Can't fire up on Ubuntu Container

### ISSUE THREAD

**Issue by ugurcemozturk** [theInfectedDrake/TIDoS-Framework#36]
Hey, 
firstly thanks for open sourcing this awesome repo.

 - I'm working with an IOS one. To run your tool flawless, I've just created an Ubuntu image on Docker.
After successful installation, when I try to run tidos, it gives me the following;

>  File "/opt/tidos/tidos.py", line 13, in <module> from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 31, in <module> from core.Auxillaries.auxil import *
  File "/opt/tidos/core/Auxillaries/auxil.py", line 21, in <module> from honeypot import *
  File "modules/0x05-Auxillaries+PF6/honeypot.py", line 12, in <module> import requests 
  ImportError: No module named requests

- python is version 2.7.

What could be the reason of this?
Thx.
ugurcem

![image](https://user-images.githubusercontent.com/6145239/46312276-49af6880-c5cd-11e8-9d31-e9250c474dc5.png)

**Comment by AlecsGherghel** [comment]
Seems like requests library is missing. You could try to manually install it `sudo pip install requests` but I don't recommend that since it seems that the framework uses it's own version of requests (a fork?).

You can try to `cd lib/requests/ && sudo python2 setup.py install` and see if that crashes somehow.

**Comment by theInfectedDrake** [comment]
The error you're getting is due to a local dependency error of a missing module called requests. TIDoS uses its own library of an enhanced modified `requests` version, but it should work fine with the latest version of `requests`, so make sure your Dockerfile does contain a line for installation of the `requests` library via `pip`.

**Comment by ugurcemozturk** [comment]
I've just run with an Ubuntu Linux without DFile. 
So it's better to create a dockerfile that runs on top of Alpine.
Maybe I can contribute your project with this tiny Dockerfile?

Because I love your work as Kanye West loves Kanye West.
thx,
Ugurcem

**Comment by ugurcemozturk** [comment]
UPDATE:

Even I tried with Alpine && added pip install requests to DOckerfile or even install pip inside the container gives me the same result.

I'll keep you posted.

**Comment by theInfectedDrake** [comment]
You may want to add `pip2 install requests` instead of `pip install requests`, since your default `pip` version might be 3.x. The TIDoS engine runs on default Python 2.x version. 

However the work of porting TIDoS from Python 2.x to 3.x has already begun, thanks to @cclauss for rolling this in motion via #37.

**Comment by ugurcemozturk** [comment]
@theInfectedDrake 
So the current situation is to wait for  #38 

But I'm going to fork and create a Dockerfile to proceed faster.

Thx;)
ugurcem
